apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-data-app1-deployment
  labels:
    app: static-data-app1
spec:
  replicas: 2
  selector:
    matchLabels:
      name: static-data-app1-pod
      app: static-data-app1
  template:
    metadata: 
      name: static-data-app1-pod
      labels:
        name: static-data-app1-pod
        app: static-data-app1
    spec:
      containers:
      - name: static-data-app1
        image: bashkimkasa/static-data-app1
        ports:
        - containerPort: 8082